services:
  _defaults:
    autowire: true
    autoconfigure: true
  CJDevStudios\EntityManagementBundle\:
    resource: '../src/*'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Tests/'
